version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: 'mokuteki'
      POSTGRES_PASSWORD: 'pass123'
      POSTGRES_DB: 'propagated-test'
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
